### ISSUE TITLE
Unable to access Google Drive files

### ISSUE THREAD

**Issue by pixel-lt** [chogovadze/Deep-Illuminator#1]
Hi, 
      I am trying to test your code but I am unable to access the google drive for the pretrained model. If you have time, could you pls send this files to me(liaoting@whu.edu.cn).

Thanks again for the project!

Regards,

**Comment by chogovadze** [comment]
Hello,
Thank you for your interest in this project! Unfortunately, at this time, the model weights are only offered on the google drive. The access rights should be working now.
